[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/database"
  to = "/.netlify/functions/database"
  status = 200

[[redirects]]
  from = "/page/*"
  to = "/.netlify/functions/page/:splat"
  status = 200
